/* Problem 2 - Even Fibonacci Numbers

Solved.

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

class Problem_002 {
	public static void main(String args[]){
		
		int total = 0;
		int numA = 1;
		int numB = 1;
		int holder = 0;
		
		while (numA + numB < 4000000){
			numB = numA + numB;
			if (numB % 2 == 0)
				total += numB;
			holder = numA;
			numA = numB;
			numB = holder;
		}
		System.out.println(total);
	}
}
